name: <WORKFLOW_NAME>

on:
  push:
    branches:
      - <BRANCH_NAME>
jobs:
  deploy_cloud_run_function:
    runs-on: ubuntu-latest

    env:
      CLOUD_RUN_FUNCTION_NAME: <FUNCTION_NAME>
      TARGET_FUNCTION: <TARGET_FUNCTION_NAME>
      REGION: <REGION>
      PROJECT: <PROJECT_ID>

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set Google Cloud Project
        run: gcloud config set project $PROJECT
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Install beta components
        run: gcloud components install beta --quiet

      - name: Deploy to Cloud Run Function
        run: |
          gcloud beta run deploy $CLOUD_RUN_FUNCTION_NAME \
          --source . \
          --function $TARGET_FUNCTION \
          --base-image python312 \
          --region $REGION \
          --allow-unauthenticated \
          --verbosity=debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}
